# Generated by Django 3.2.4 on 2021-06-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New_Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('time', models.CharField(max_length=60)),
                ('year', models.IntegerField(blank=True)),
                ('illness', models.IntegerField(null=True)),
            ],
        ),
    ]
